
spring:
  kafka:
    bootstrap-servers: {???_??_??} # cluster settings -> Endpoints?? ?? ??
  properties:
    sasl:
      jaas:
        config: org.apache.kafka.common.security.plain.PlainLoginModule required username='{??_API_Key}' password='{??_API_secret}'; # ???? ??? ???? ???.
